### ISSUE TITLE
Las sentencias Entonces solo deben verificar resultados

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp3#2]
La sentencias
https://github.com/acurber91/tsiot_tp3/blob/ec77f12e8d7e0e30c478de8580a08eb53f2754fc/features/edicion.feature#L15-L16
son en realidad  dos sentencias `Cuando` mezcladas con una `Entonces`. Esto debería reescribirse como

```Gherkin
    Cuando si se elimina la clave "clave",    
    Y si se busca la clave "clave", 
    Entonces obtengo el valor NaN.
```
Dado que utilizaste comas para marcar correctamente el texto en castellano, no deberías tenes ninguna sentencia con dos coma en la misma linea, toda deberían desdoblarse

**Comment by acurber91** [comment]
Lo solucioné de esta manera:

`  Cuando se elimina la clave "clave",
    Entonces si se busca la clave "clave" se obtiene NaN.`

Ya que la sentencia "Y" necesita verificar algún resultado. Como ese resultado se verifica recién en la sentencia final, no había forma de dividir esas sentencias en tres partes.
