### ISSUE TITLE
Esta sentencia debería eliminarse

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp3#3]
En este escenario

https://github.com/acurber91/tsiot_tp3/blob/ec77f12e8d7e0e30c478de8580a08eb53f2754fc/features/edicion.feature#L13-L16

la sentencia 

https://github.com/acurber91/tsiot_tp3/blob/ec77f12e8d7e0e30c478de8580a08eb53f2754fc/features/edicion.feature#L14

No cambia en nada el resultado de la prueba, yo creo que debería eliminarse porque solo confunde.

**Comment by acurber91** [comment]
Coincido, no sé por que la incorporé en la prueba.
