### ISSUE TITLE
Los pasos piden unificarse en un solo archivo

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp3#4]
No es necesario que los pasos este divididos en diferentes archivos en concordancia con los archivos de funcionalidades. En general si se dividen los pasos en diferentes archivos se lo hace para probar diferentes componentes, pero como esto se trata de un solo componente, generar un solo archivos de pasos es menos trabajo.

**Comment by acurber91** [comment]
Perfecto, buena aclaración. Pensé que para mejorar la modularidad del proyecto era mejor también dividir los pasos. Todos los pasos están ahora bajo un nuevo archivo llamado `lista_steps.js`.

**Comment by evolentini** [comment]
En realidad es algo que vos podes elegir, pero como juntar mucho no es bueno, atomizar demasiado tampoco lo es. Pienso que agrupar todos los pasos que interactuando con una clase o un archivo es, más o menos, la regla.
